export const DEMO_REF_PREFIX = 'DEMO-';

export const DEMO_PARQUES = [
  {
    key: 'parqueBajio',
    referencia: `${DEMO_REF_PREFIX}PARQUE-BAJIO-SILAO`,
    nombre: 'Parques del Bajío - Silao',
    ubicacion: 'Blvd. El Mezquital 234, Silao, GTO',
    m2Totales: 40600,
    m2Rentados: 31900,
    administrador: 'Lic. Roberto Sánchez',
    fotoEntradaUrl:
      'https://images.unsplash.com/photo-1595844730298-6cff2533fccc?auto=format&fit=crop&w=1200&q=80',
  },
  {
    key: 'parqueGuadalajaraPark',
    referencia: `${DEMO_REF_PREFIX}PARQUE-GUADALAJARA-PARK`,
    nombre: 'Guadalajara Park',
    ubicacion: 'Guadalajara, Jalisco',
    m2Totales: 72000,
    m2Rentados: 68401,
    administrador: 'Lic. Roberto Sánchez',
    fotoEntradaUrl: '/images/parks-industrial/guadalajara-park-entrada.png',
  },
  {
    key: 'parqueElSaltoParkIII',
    referencia: `${DEMO_REF_PREFIX}PARQUE-EL-SALTO-III`,
    nombre: 'El Salto Park III',
    ubicacion: 'Carretera Guadalajara-El Salto Km 8, El Salto, Jalisco',
    m2Totales: 198000,
    m2Rentados: 101885,
    administrador: 'Lic. Roberto Sánchez',
    fotoEntradaUrl: '/images/parks-industrial/el-salto-park-iii-entrada.png',
  },
  {
    key: 'parqueTMexPark',
    referencia: `${DEMO_REF_PREFIX}PARQUE-T-MEXPARK`,
    nombre: 'T-MexPark',
    ubicacion: 'Nextlalpan, Área Metropolitana de Ciudad de México',
    m2Totales: 220000,
    m2Rentados: 66382,
    administrador: 'Lic. Roberto Sánchez',
    fotoEntradaUrl: '/images/parks-industrial/t-mexpark-entrada.png',
  },
  {
    key: 'parqueTolucaParksIII',
    referencia: `${DEMO_REF_PREFIX}PARQUE-TOLUCA-PARKS-III`,
    nombre: 'Toluca Parks III',
    ubicacion: 'Toluca, Área Metropolitana de Ciudad de México',
    m2Totales: 95000,
    m2Rentados: 60555,
    administrador: 'Lic. Roberto Sánchez',
    fotoEntradaUrl: '/images/parks-industrial/toluca-parks-iii-entrada.png',
  },
  {
    key: 'parqueTultiParkII',
    referencia: `${DEMO_REF_PREFIX}PARQUE-TULTIPARK-II`,
    nombre: 'TultiPark II',
    ubicacion: 'Blvd. Tultitlán 450, Tultitlán, Estado de México',
    m2Totales: 54000,
    m2Rentados: 47256,
    administrador: 'Lic. Roberto Sánchez',
    fotoEntradaUrl: '/images/parks-industrial/tultipark-ii-entrada.png',
  },
  {
    key: 'parqueTlaneParkIV',
    referencia: `${DEMO_REF_PREFIX}PARQUE-TLANEPARK-IV`,
    nombre: 'TlanePark IV',
    ubicacion: 'Periférico Norte 85, Tlalnepantla, Estado de México',
    m2Totales: 48000,
    m2Rentados: 45725,
    administrador: 'Lic. Roberto Sánchez',
    fotoEntradaUrl: '/images/parks-industrial/tlanepark-iv-entrada.png',
  },
  {
    key: 'parqueGuadalupeParkI',
    referencia: `${DEMO_REF_PREFIX}PARQUE-GUADALUPE-PARK-I`,
    nombre: 'GuadalupePark I',
    ubicacion: 'Av. del Parque Industrial 200, Guadalupe, Nuevo León',
    m2Totales: 95000,
    m2Rentados: 92213,
    administrador: 'Ing. Laura Mendoza',
    fotoEntradaUrl: '/images/parks-industrial/guadalupe-park-i-entrada.png',
  },
] as const;

export const DEMO_BROKERS = [
  {
    key: 'brokerNewmark',
    empresa: 'Newmark',
    contacto: 'Carlos Mendoza',
    email: 'cmendoza@newmark.mx',
    firma: 'Newmark',
  },
  {
    key: 'brokerCbre',
    empresa: 'CBRE',
    contacto: 'Ana Ruiz',
    email: 'aruiz@cbre.com',
    firma: 'CBRE',
  },
  {
    key: 'brokerIndependiente',
    empresa: 'Industria Libre Brokers',
    contacto: 'Jorge Vega',
    email: 'jorge@industrialibre.mx',
    firma: 'Independiente',
  },
] as const;
