// Naves disponibles en catálogo público Parks Industrial (Jun 2025)
// https://industrial.parks.com.mx/propiedades

export type DemoNaveEstatus = 'Disponible' | 'Rentada' | 'En negociación';

export type DemoNaveDefinition = {
  key: string;
  identificador: string;
  parqueKey: string;
  m2: number;
  estatus: DemoNaveEstatus;
  esPropiedadFuno: boolean;
  precioBaseUsd: number;
};

export const DEMO_NAVE_DEFINITIONS: DemoNaveDefinition[] = [
  {
    key: 'naveGdl001',
    identificador: 'Bodega B-5',
    parqueKey: 'parqueGuadalajaraPark',
    m2: 1254,
    estatus: 'Rentada',
    esPropiedadFuno: false,
    precioBaseUsd: 0.85,
  },
  {
    key: 'naveGdl002',
    identificador: 'Patio',
    parqueKey: 'parqueGuadalajaraPark',
    m2: 2345,
    estatus: 'Rentada',
    esPropiedadFuno: false,
    precioBaseUsd: 0.9,
  },
  {
    key: 'naveGdl003',
    identificador: 'Nave F',
    parqueKey: 'parqueElSaltoParkIII',
    m2: 46224.76,
    estatus: 'En negociación',
    esPropiedadFuno: false,
    precioBaseUsd: 0.82,
  },
  {
    key: 'naveGdl004',
    identificador: 'Nave D-2',
    parqueKey: 'parqueElSaltoParkIII',
    m2: 49890.22,
    estatus: 'Disponible',
    esPropiedadFuno: false,
    precioBaseUsd: 0.88,
  },
  {
    key: 'naveTMex001',
    identificador: 'Nave C-3',
    parqueKey: 'parqueTMexPark',
    m2: 44657.61,
    estatus: 'Disponible',
    esPropiedadFuno: false,
    precioBaseUsd: 0.92,
  },
  {
    key: 'naveTMex002',
    identificador: 'Nave B-3',
    parqueKey: 'parqueTMexPark',
    m2: 51036,
    estatus: 'Disponible',
    esPropiedadFuno: false,
    precioBaseUsd: 0.9,
  },
  {
    key: 'naveTMex003',
    identificador: 'Nave B-2B',
    parqueKey: 'parqueTMexPark',
    m2: 6955.97,
    estatus: 'Disponible',
    esPropiedadFuno: false,
    precioBaseUsd: 0.91,
  },
  {
    key: 'naveTMex004',
    identificador: 'Nave C-4',
    parqueKey: 'parqueTMexPark',
    m2: 50968.35,
    estatus: 'Disponible',
    esPropiedadFuno: false,
    precioBaseUsd: 0.9,
  },
  {
    key: 'naveToluca001',
    identificador: 'Nave D',
    parqueKey: 'parqueTolucaParksIII',
    m2: 34445.48,
    estatus: 'Disponible',
    esPropiedadFuno: false,
    precioBaseUsd: 0.88,
  },
  {
    key: 'naveTulti001',
    identificador: 'Nave C4',
    parqueKey: 'parqueTultiParkII',
    m2: 760,
    estatus: 'Rentada',
    esPropiedadFuno: false,
    precioBaseUsd: 0.87,
  },
  {
    key: 'naveTulti002',
    identificador: 'Nave E4-A',
    parqueKey: 'parqueTultiParkII',
    m2: 5984.33,
    estatus: 'Rentada',
    esPropiedadFuno: false,
    precioBaseUsd: 0.95,
  },
  {
    key: 'naveTlane001',
    identificador: 'Nave PA-1B',
    parqueKey: 'parqueTlaneParkIV',
    m2: 2275.28,
    estatus: 'Disponible',
    esPropiedadFuno: false,
    precioBaseUsd: 0.91,
  },
  {
    key: 'naveMty001',
    identificador: 'Bodega 05AM200',
    parqueKey: 'parqueGuadalupeParkI',
    m2: 2787.09,
    estatus: 'Rentada',
    esPropiedadFuno: true,
    precioBaseUsd: 1.1,
  },
  {
    key: 'naveBajio01',
    identificador: 'Nave 1',
    parqueKey: 'parqueBajio',
    m2: 3500,
    estatus: 'Rentada',
    esPropiedadFuno: false,
    precioBaseUsd: 0.86,
  },
  {
    key: 'naveBajio02',
    identificador: 'Nave 2',
    parqueKey: 'parqueBajio',
    m2: 2800,
    estatus: 'Rentada',
    esPropiedadFuno: false,
    precioBaseUsd: 0.87,
  },
  {
    key: 'naveBajio03',
    identificador: 'Nave 3',
    parqueKey: 'parqueBajio',
    m2: 4200,
    estatus: 'Rentada',
    esPropiedadFuno: false,
    precioBaseUsd: 0.9,
  },
  {
    key: 'naveBajio04',
    identificador: 'Nave 4',
    parqueKey: 'parqueBajio',
    m2: 3100,
    estatus: 'Disponible',
    esPropiedadFuno: false,
    precioBaseUsd: 0.88,
  },
  {
    key: 'naveBajio05',
    identificador: 'Nave 5',
    parqueKey: 'parqueBajio',
    m2: 2500,
    estatus: 'Rentada',
    esPropiedadFuno: false,
    precioBaseUsd: 0.85,
  },
  {
    key: 'naveBajio06',
    identificador: 'Nave 6',
    parqueKey: 'parqueBajio',
    m2: 5000,
    estatus: 'Rentada',
    esPropiedadFuno: false,
    precioBaseUsd: 0.92,
  },
  {
    key: 'naveBajio07',
    identificador: 'Nave 7',
    parqueKey: 'parqueBajio',
    m2: 3800,
    estatus: 'Disponible',
    esPropiedadFuno: false,
    precioBaseUsd: 0.89,
  },
  {
    key: 'naveBajio08',
    identificador: 'Nave 8',
    parqueKey: 'parqueBajio',
    m2: 2900,
    estatus: 'Rentada',
    esPropiedadFuno: false,
    precioBaseUsd: 0.86,
  },
  {
    key: 'naveBajio09',
    identificador: 'Nave 9',
    parqueKey: 'parqueBajio',
    m2: 4500,
    estatus: 'Rentada',
    esPropiedadFuno: false,
    precioBaseUsd: 0.91,
  },
  {
    key: 'naveBajio10',
    identificador: 'Nave 10',
    parqueKey: 'parqueBajio',
    m2: 3200,
    estatus: 'Disponible',
    esPropiedadFuno: false,
    precioBaseUsd: 0.87,
  },
  {
    key: 'naveBajio11',
    identificador: 'Nave 11',
    parqueKey: 'parqueBajio',
    m2: 2700,
    estatus: 'Rentada',
    esPropiedadFuno: false,
    precioBaseUsd: 0.85,
  },
  {
    key: 'naveBajio12',
    identificador: 'Nave 12',
    parqueKey: 'parqueBajio',
    m2: 3600,
    estatus: 'Rentada',
    esPropiedadFuno: false,
    precioBaseUsd: 0.89,
  },
];
